#ifndef SWEEPFREQUENCYGENERATOR_GLOBAL_H
#define SWEEPFREQUENCYGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SWEEPFREQUENCYGENERATOR_LIB
# define SWEEPFREQUENCYGENERATOR_EXPORT Q_DECL_EXPORT
#else
# define SWEEPFREQUENCYGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // SWEEPFREQUENCYGENERATOR_GLOBAL_H
