#ifndef HIGHFREQUENCYSIGNALSGENERATOR_GLOBAL_H
#define HIGHFREQUENCYSIGNALSGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HIGHFREQUENCYSIGNALSGENERATOR_LIB
# define HIGHFREQUENCYSIGNALSGENERATOR_EXPORT Q_DECL_EXPORT
#else
# define HIGHFREQUENCYSIGNALSGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // HIGHFREQUENCYSIGNALSGENERATOR_GLOBAL_H
