#ifndef BANDPASSFILTER2_GLOBAL_H
#define BANDPASSFILTER2_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BANDPASSFILTER2_LIB
# define BANDPASSFILTER2_EXPORT Q_DECL_EXPORT
#else
# define BANDPASSFILTER2_EXPORT Q_DECL_IMPORT
#endif

#endif // BANDPASSFILTER2_GLOBAL_H
