#ifndef BANDPASSFILTER_GLOBAL_H
#define BANDPASSFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BANDPASSFILTER_LIB
# define BANDPASSFILTER_EXPORT Q_DECL_EXPORT
#else
# define BANDPASSFILTER_EXPORT Q_DECL_IMPORT
#endif

#endif // BANDPASSFILTER_GLOBAL_H
