#ifndef COAXIALWAVEGUIDETRANSITION_GLOBAL_H
#define COAXIALWAVEGUIDETRANSITION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COAXIALWAVEGUIDETRANSITION_LIB
# define COAXIALWAVEGUIDETRANSITION_EXPORT Q_DECL_EXPORT
#else
# define COAXIALWAVEGUIDETRANSITION_EXPORT Q_DECL_IMPORT
#endif

#endif // COAXIALWAVEGUIDETRANSITION_GLOBAL_H
