#ifndef WAVEGUIDESLOTANTENNA_GLOBAL_H
#define WAVEGUIDESLOTANTENNA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WAVEGUIDESLOTANTENNA_LIB
# define WAVEGUIDESLOTANTENNA_EXPORT Q_DECL_EXPORT
#else
# define WAVEGUIDESLOTANTENNA_EXPORT Q_DECL_IMPORT
#endif

#endif // WAVEGUIDESLOTANTENNA_GLOBAL_H
