#ifndef REDUCTIONINDICATOR_GLOBAL_H
#define REDUCTIONINDICATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef REDUCTIONINDICATOR_LIB
# define REDUCTIONINDICATOR_EXPORT Q_DECL_EXPORT
#else
# define REDUCTIONINDICATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // REDUCTIONINDICATOR_GLOBAL_H
