#ifndef MICROSTRIPRESONATOR_GLOBAL_H
#define MICROSTRIPRESONATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MICROSTRIPRESONATOR_LIB
# define MICROSTRIPRESONATOR_EXPORT Q_DECL_EXPORT
#else
# define MICROSTRIPRESONATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // MICROSTRIPRESONATOR_GLOBAL_H
