#ifndef WAVEGUIDETBRIDGE_GLOBAL_H
#define WAVEGUIDETBRIDGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WAVEGUIDETBRIDGE_LIB
# define WAVEGUIDETBRIDGE_EXPORT Q_DECL_EXPORT
#else
# define WAVEGUIDETBRIDGE_EXPORT Q_DECL_IMPORT
#endif

#endif // WAVEGUIDETBRIDGE_GLOBAL_H
