#ifndef WAVEGUIDEPOWERDIVIDER_GLOBAL_H
#define WAVEGUIDEPOWERDIVIDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WAVEGUIDEPOWERDIVIDER_LIB
# define WAVEGUIDEPOWERDIVIDER_EXPORT Q_DECL_EXPORT
#else
# define WAVEGUIDEPOWERDIVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // WAVEGUIDEPOWERDIVIDER_GLOBAL_H
